version: '3.8'
services:
    blog:
        build: .
        user: app
        expose:
            - 9000
        volumes:
            - ./:/app

    proxy:
        image: nginx:1.27.0
        ports:
            - '80:80'
        volumes:
            - ./:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - blog

    db:
        image: postgres:16.3
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db-data:
